name = "dealspark-api"
main = "src/index.js"
compatibility_date = "2026-10-07"

[vars]
# Set production secrets with Wrangler/GitHub Actions:
# ADMIN_TOKEN
# TWILIO_AUTH_TOKEN
# TWILIO_SITE_KEY

[[d1_databases]]
binding = "DB"
database_name = "dealspark"
database_id = "0b366288-652e-43fb-b4a0-d5484f2916c3"
migrations_dir = "migrations"
