const enc=new TextEncoder();
export const cors={"access-control-allow-origin":"*","access-control-allow-headers":"content-type,authorization","access-control-allow-methods":"GET,POST,PATCH,OPTIONS"};
export function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8",...cors}})}
export function options(){return new Response(null,{status:204,headers:cors})}
export async function readBody(request){try{return await request.json()}catch{return {}}}
export async function hashPassword(password,salt){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:enc.encode(salt),iterations:100000,hash:"SHA-256"},key,256);return [...new Uint8Array(bits)].map(b=>b.toString(16).padStart(2,"0")).join("")}
export async function verifyPassword(password,salt,expected){if(!salt||!expected)return false;const actual=await hashPassword(password,salt);if(actual.length!==expected.length)return false;let diff=0;for(let i=0;i<actual.length;i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);return diff===0}
export async function digestToken(token){const d=await crypto.subtle.digest("SHA-256",enc.encode(token));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")}
export function randomToken(){const a=crypto.getRandomValues(new Uint8Array(32));return [...a].map(b=>b.toString(16).padStart(2,"0")).join("")}
export async function createSession(env,userId,workspaceId){const token=randomToken(),now=new Date().toISOString(),expires=new Date(Date.now()+30*24*60*60*1000).toISOString(),tokenHash=await digestToken(token);await env.DB.prepare("INSERT INTO sessions (id,user_id,expires_at,created_at,token_hash,workspace_id) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),userId,expires,now,tokenHash,workspaceId).run();return token}
export async function getSession(request,env){const auth=request.headers.get("authorization")||"",token=auth.startsWith("Bearer ")?auth.slice(7).trim():"";if(!token)return null;const tokenHash=await digestToken(token);return await env.DB.prepare("SELECT s.user_id,s.workspace_id,s.expires_at,u.email,u.business_id,b.name AS business_name FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN businesses b ON b.id=u.business_id WHERE s.token_hash=? AND s.expires_at>? LIMIT 1").bind(tokenHash,new Date().toISOString()).first()}
export async function ensureWorkspace(env,email,businessId,name){let w=await env.DB.prepare("SELECT id,name FROM workspaces WHERE lower(owner_email)=? LIMIT 1").bind(email.toLowerCase()).first();if(!w){const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO workspaces (id,name,owner_email,created_at) VALUES (?,?,?,?)").bind(id,name||"DealSpark Workspace",email.toLowerCase(),now).run();w={id,name:name||"DealSpark Workspace"};}return w}
export async function ensureBusiness(env,name,timezone="America/Toronto",phone=""){const id=crypto.randomUUID(),key="ds_"+randomToken(),now=new Date().toISOString();await env.DB.prepare("INSERT INTO businesses (id,name,public_key,timezone,phone,created_at) VALUES (?,?,?,?,?,?)").bind(id,name||"DealSpark Workspace",key,timezone,phone,now).run();return {id,public_key:key,name:name||"DealSpark Workspace"}}
